# Generated by Django 3.2.4 on 2021-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMC_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
