# Generated by Django 3.2.4 on 2021-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMC_app', '0002_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imc',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
